### ISSUE TITLE
Suggestion: add C/W for the vertical scanner

### ISSUE THREAD

**Issue by TradingDominion** [ninjaspread/ns#2]
Suggestion: add C/W for the vertical scanner

**Comment by ninjaspread** [comment]
C/W stands for credit / width in a short vertical spread that is embedded in ie. diagonal, butterfly, etc. 
But for simple long verticals, there is no embedded credit vertical. If you want to see how much you get by the short leg, please check "+/-" column which shows you "short option price / long option price" so essentially how much (in percentage terms) you have lowered your initial debit. 

Is this what you are looking for?

**Comment by TradingDominion** [comment]
Even though there is no embedded spread, being able to compare the credit received versus the width of the strikes in the vertical is still useful to some people.
TastyTrade popularized this approach.
For example, when selling a put credit spread, they tend to suggest focusing on verticals which give you a C/W of 30%.
The concept is still the same: it's a matter of getting sufficient credit for the risk you're taking.

**Comment by ninjaspread** [comment]
I have developed the C/W feature for Verticals as well. Here is how it works:

In case of credit spread (Bear Call, Bull Put) C/W is calculated by dividing the credit you receive from selling the vertical with the width of the spread. If you are scanning for a debit spread (Bull Call, Bear Put), C/W will show you how much is the short leg's credit compared to the width of the spread.

**Comment by TradingDominion** [comment]
My suggestion would be to keep it consistent.

C/W is comparing the credit received for the spread through to the width between the strikes.

When looking at a credit spread then some users will want to have at least a certain C/W percentage (eg 30%) in order to justify selling that spread for the amount of risk being taken (represented by the width of the strikes).

When looking at a debit spread, rather than looking just the short strike, I'd suggest keeping the concept consistent, and you'd therefore look at the debit paid for the spread and compare that to the width of the strikes.
You can consider a debit to be a "negative credit".
For a debit spread you'd therefore be looking for a low C/W, which would imply a low cost (debit paid) for a wide spread.

**Comment by ninjaspread** [comment]
Ok I changed that way. This way this gets similar to R/R, but shows you something different. 
Please test to see if this is what you are looking for.
Thanks for your suggestions.

**Comment by TradingDominion** [comment]
Yes, the implementation looks fine.
Thanks.

**Comment by ninjaspread** [comment]
Great, thanks for the valuable feedback.
